# OrgOS Export Manifest
# エクスポート対象ファイルの定義

version_file: ".ai/VERSION.yaml"

# publish: 公開リポジトリに同期するファイル
publish:
  # コア設定
  - ".ai/VERSION.yaml"
  - ".ai/CHANGELOG.md"
  - ".orgos-manifest.yaml"
  - "CLAUDE.md"
  - "AGENTS.md"
  - "ORGOS_QUICKSTART.md"
  - "README.md"
  # リソーステンプレート
  - ".ai/RESOURCES/README.md"
  # 初期テンプレート（/org-import で初回のみ展開）
  - ".ai/TEMPLATES/BRIEF.md"
  - ".ai/TEMPLATES/CONTROL.yaml"
  - ".ai/TEMPLATES/DASHBOARD.md"
  - ".ai/TEMPLATES/OWNER_INBOX.md"
  - ".ai/TEMPLATES/OWNER_COMMENTS.md"
  # コマンド（通常利用: 5コマンド）
  - ".claude/commands/org-start.md"
  - ".claude/commands/org-tick.md"
  - ".claude/commands/org-brief.md"
  - ".claude/commands/org-import.md"
  - ".claude/commands/org-settings.md"
  # コマンド（Dev環境: +3コマンド）
  - ".claude/commands/org-release.md"
  - ".claude/commands/org-publish.md"
  - ".claude/commands/org-admin.md"
  # エージェント（13エージェント）
  - ".claude/agents/org-planner.md"
  - ".claude/agents/org-architect.md"
  - ".claude/agents/org-integrator.md"
  - ".claude/agents/org-scribe.md"
  - ".claude/agents/org-os-maintainer.md"
  - ".claude/agents/org-implementer.md"
  - ".claude/agents/org-reviewer.md"
  - ".claude/agents/org-security-reviewer.md"
  - ".claude/agents/org-build-fixer.md"
  - ".claude/agents/org-refactor-cleaner.md"
  - ".claude/agents/org-tdd-coach.md"
  - ".claude/agents/org-e2e-runner.md"
  - ".claude/agents/org-doc-updater.md"
  # Skills（技術知識ベース）
  - ".claude/skills/coding-standards.md"
  - ".claude/skills/backend-patterns.md"
  - ".claude/skills/frontend-patterns.md"
  - ".claude/skills/tdd-workflow.md"
  # Rules（品質基準）
  - ".claude/rules/security.md"
  - ".claude/rules/testing.md"
  - ".claude/rules/review-criteria.md"
  - ".claude/rules/patterns.md"
  - ".claude/rules/agent-coordination.md"
  - ".claude/rules/performance.md"
  - ".claude/rules/literacy-adaptation.md"
  - ".claude/rules/owner-task-minimization.md"
  - ".claude/rules/ai-driven-development.md"
  - ".claude/rules/eval-loop.md"
  # 設定
  - ".claude/settings.json"
  # Git hooks
  - ".githooks/pre-push"
  # GitHub Actions
  - ".github/workflows/release.yaml"
  - ".github/workflows/test.yaml"

# core: 上書きしてOK（OrgOSのコア機能）- /org-import用
core:
  - ".ai/VERSION.yaml"
  - ".ai/CHANGELOG.md"
  - ".ai/RESOURCES/README.md"
  - ".claude/commands/org-start.md"
  - ".claude/commands/org-tick.md"
  - ".claude/commands/org-brief.md"
  - ".claude/commands/org-import.md"
  - ".orgos-manifest.yaml"
  - "CLAUDE.md"

# preserve: 既存があればスキップ（プロジェクト固有データ）
preserve:
  - ".ai/PROJECT.md"
  - ".ai/TASKS.yaml"
  - ".ai/DECISIONS.md"
  - ".ai/RISKS.md"
  - ".ai/DASHBOARD.md"
  - ".ai/OWNER_INBOX.md"
  - ".ai/OWNER_COMMENTS.md"
  - ".ai/CONTROL.yaml"
  - ".ai/STATUS.yaml"
  - ".ai/RUN_LOG.md"

# templates: 初回のみ展開（既存があればスキップ）- /org-import用
templates:
  - source: ".ai/TEMPLATES/BRIEF.md"
    dest: ".ai/BRIEF.md"
  - source: ".ai/TEMPLATES/CONTROL.yaml"
    dest: ".ai/CONTROL.yaml"
  - source: ".ai/TEMPLATES/DASHBOARD.md"
    dest: ".ai/DASHBOARD.md"
  - source: ".ai/TEMPLATES/OWNER_INBOX.md"
    dest: ".ai/OWNER_INBOX.md"
  - source: ".ai/TEMPLATES/OWNER_COMMENTS.md"
    dest: ".ai/OWNER_COMMENTS.md"

# create_dirs: インポート時に作成するディレクトリ
create_dirs:
  - ".ai"
  - ".ai/RESOURCES"
  - ".ai/RESOURCES/docs"
  - ".ai/RESOURCES/designs"
  - ".ai/RESOURCES/references"
  - ".ai/RESOURCES/code-samples"
  - ".ai/TEMPLATES"
  - ".claude/commands"
  - ".claude/agents"
