#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
APPLIED_DIR="${APPLIED_DIR:-$REPO_ROOT/.ai/EVOLUTION/applied}"

usage() {
  cat <<'EOF'
Usage: bash scripts/evolution/rollback.sh <record_id|record_path>

Restores the target file from the application record's before snapshot, verifies
the before_checksum, increments the consecutive revert counter, and back-writes
rollback_ref into the application record.
EOF
}

if [[ $# -ne 1 ]]; then
  usage >&2
  exit 2
fi

RECORD_REF="$1"
export REPO_ROOT APPLIED_DIR RECORD_REF

python3 - <<'PY'
from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

repo_root = Path(os.environ["REPO_ROOT"]).resolve()
applied_dir = Path(os.environ["APPLIED_DIR"])
if not applied_dir.is_absolute():
    applied_dir = repo_root / applied_dir
record_ref = os.environ["RECORD_REF"]


def utc_now() -> datetime:
    override = os.environ.get("ORGOS_ROLLBACK_NOW")
    if override:
        try:
            return datetime.fromisoformat(override.replace("Z", "+00:00")).astimezone(timezone.utc)
        except ValueError:
            print(
                json.dumps(
                    {
                        "level": "error",
                        "trace": "rollback",
                        "event": "failed",
                        "error_class": "invalid_argument",
                        "message": "ORGOS_ROLLBACK_NOW is not ISO8601",
                        "recovery": "Unset it or pass an ISO8601 timestamp.",
                    },
                    ensure_ascii=False,
                    sort_keys=True,
                )
            )
            raise SystemExit(1)
    return datetime.now(timezone.utc).replace(microsecond=0)


def log(level: str, event: str, **fields: Any) -> None:
    payload = {
        "level": level,
        "trace": "rollback",
        "event": event,
        "at": utc_now().isoformat().replace("+00:00", "Z"),
    }
    payload.update(fields)
    print(json.dumps(payload, ensure_ascii=False, sort_keys=True))


def fail(kind: str, message: str, recovery: str, exit_code: int = 1) -> None:
    log("error", "failed", error_class=kind, message=message, recovery=recovery)
    raise SystemExit(exit_code)


def rel_to_repo(path: Path) -> str:
    return path.resolve().relative_to(repo_root).as_posix()


def record_path() -> Path:
    candidate = Path(record_ref)
    if candidate.suffix in {".yaml", ".yml"} or "/" in record_ref:
        path = candidate if candidate.is_absolute() else repo_root / candidate
    else:
        path = applied_dir / f"{record_ref}.yaml"
    if not path.exists():
        fail("missing_input", f"application record not found: {path}", "Pass an existing AR-YYYY-MM-DD-NNN id or path.", 2)
    return path


def load_yaml(path: Path) -> dict[str, Any]:
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as exc:
        fail("invalid_input", f"record YAML is invalid: {exc}", "Repair the application record.")
    if not isinstance(data, dict):
        fail("invalid_input", "record YAML is not an object", "Repair the application record.")
    return data


def write_yaml(path: Path, data: dict[str, Any]) -> None:
    path.write_text(yaml.safe_dump(data, sort_keys=False, allow_unicode=True), encoding="utf-8")


def sha256_path(path: Path, exists: bool) -> str:
    if not exists:
        return hashlib.sha256(b"").hexdigest()
    return hashlib.sha256(path.read_bytes()).hexdigest()


def target_path(record: dict[str, Any]) -> tuple[str, Path]:
    target = str(record.get("target_file") or "").strip()
    if not target:
        fail("schema_validation", "record target_file is missing", "Use a valid application record.")
    candidate = Path(target)
    if candidate.is_absolute():
        fail("path_violation", f"absolute target_file is not allowed: {target}", "Use a repository-relative target path.")
    resolved = (repo_root / candidate).resolve()
    try:
        normalized = resolved.relative_to(repo_root).as_posix()
    except ValueError:
        fail("path_violation", f"target escapes repository: {target}", "Use a repository-relative target path.")
    return normalized, resolved


def backup_path(record: dict[str, Any]) -> Path:
    backup_ref = str(record.get("backup_ref") or "").strip()
    if not backup_ref:
        fail("schema_validation", "record backup_ref is missing", "Use a record generated by apply.sh.")
    candidate = Path(backup_ref)
    path = candidate if candidate.is_absolute() else repo_root / candidate
    if not path.exists():
        fail("missing_backup", f"before snapshot not found: {path}", "Restore the snapshot before rollback.")
    return path


def next_rollback_id() -> str:
    applied_dir.mkdir(parents=True, exist_ok=True)
    today = utc_now().date().isoformat()
    regex = re.compile(rf"^RB-{today}-([0-9]{{3}})\.yaml$")
    max_seen = 0
    for path in applied_dir.glob(f"RB-{today}-*.yaml"):
        match = regex.fullmatch(path.name)
        if match:
            max_seen = max(max_seen, int(match.group(1)))
    return f"RB-{today}-{max_seen + 1:03d}"


def state_path() -> Path:
    return applied_dir / "rollback-state.yaml"


def load_state() -> dict[str, Any]:
    path = state_path()
    if not path.exists():
        return {"consecutive_reverts": 0, "halted": False}
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError:
        data = {}
    return data if isinstance(data, dict) else {"consecutive_reverts": 0, "halted": False}


def update_state(rollback_id: str, target: str) -> dict[str, Any]:
    state = load_state()
    count = int(state.get("consecutive_reverts") or 0) + 1
    updated = {
        "consecutive_reverts": count,
        "halted": count >= 3,
        "last_rollback_ref": rollback_id,
        "last_target_file": target,
        "updated_at": utc_now().isoformat().replace("+00:00", "Z"),
    }
    write_yaml(state_path(), updated)
    return updated


def main() -> None:
    path = record_path()
    record = load_yaml(path)
    if record.get("rollback_ref") not in (None, "null", ""):
        fail("already_rolled_back", f"record already has rollback_ref: {record.get('rollback_ref')}", "Do not rollback the same record twice.")
    record_id = str(record.get("record_id") or path.stem)
    target, absolute_target = target_path(record)
    snapshot = backup_path(record)
    before_exists = bool(record.get("before_exists", True))
    expected_checksum = str(record.get("before_checksum") or "")
    if not re.fullmatch(r"[0-9a-f]{64}", expected_checksum):
        fail("schema_validation", "before_checksum is missing or invalid", "Use a valid application record.")

    log("info", "restore_started", record_id=record_id, target_file=target)
    if before_exists:
        absolute_target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(snapshot, absolute_target)
    else:
        absolute_target.unlink(missing_ok=True)

    restored_checksum = sha256_path(absolute_target, absolute_target.exists())
    if restored_checksum != expected_checksum:
        fail(
            "restore_verification_failed",
            f"restored checksum {restored_checksum} != before_checksum {expected_checksum}",
            "Inspect the snapshot and target manually before retrying.",
        )

    rollback_id = next_rollback_id()
    rollback_record_path = applied_dir / f"{rollback_id}.yaml"
    rollback_record = {
        "rollback_ref": rollback_id,
        "record_id": record_id,
        "proposal_ref": record.get("proposal_ref"),
        "target_file": target,
        "restored_checksum": restored_checksum,
        "rolled_back_at": utc_now().isoformat().replace("+00:00", "Z"),
        "rolled_back_by": "system",
        "source_record": rel_to_repo(path),
    }
    write_yaml(rollback_record_path, rollback_record)

    record["rollback_ref"] = rollback_id
    trace = record.get("rollback_trace")
    if not isinstance(trace, list):
        trace = []
    trace.append(
        {
            "at": utc_now().isoformat().replace("+00:00", "Z"),
            "event": "restored_before_snapshot",
            "rollback_ref": rollback_id,
            "restored_checksum": restored_checksum,
        }
    )
    record["rollback_trace"] = trace
    write_yaml(path, record)

    state = update_state(rollback_id, target)
    log(
        "info",
        "completed",
        record_id=record_id,
        rollback_ref=rollback_id,
        rollback_path=rel_to_repo(rollback_record_path),
        consecutive_reverts=state["consecutive_reverts"],
        halted=state["halted"],
    )


main()
PY
