#!/usr/bin/env bash
set -u

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
JOURNEYS_FILE="${JOURNEYS_FILE:-${ROOT_DIR}/.ai/JOURNEYS.yaml}"
VALIDATE_SCRIPT="${ROOT_DIR}/scripts/journeys/validate.sh"

usage() {
  printf 'Usage: bash scripts/journeys/init.sh <journey_id>\n' >&2
}

log_json() {
  local level="$1"
  local event="$2"
  local status="$3"
  local message="$4"
  printf '{"level":"%s","event":"%s","status":"%s","message":"%s"}\n' "$level" "$event" "$status" "$message" >&2
}

case "${1:-}" in
  -h|--help)
    usage
    exit 0
    ;;
  "")
    usage
    exit 2
    ;;
esac

if [[ $# -ne 1 ]]; then
  usage
  exit 2
fi

JOURNEY_ID="$1"

if [[ ! "$JOURNEY_ID" =~ ^J-[A-Z0-9-]+$ ]]; then
  log_json error journey_init failed "journey_id must match ^J-[A-Z0-9-]+$"
  exit 1
fi

if ! command -v ruby >/dev/null 2>&1; then
  log_json error journey_init failed "ruby is required"
  exit 1
fi

if [[ -L "$JOURNEYS_FILE" ]]; then
  log_json error journey_init failed "refusing to write through symlink"
  exit 1
fi

ruby - "$JOURNEYS_FILE" "$JOURNEY_ID" <<'RUBY'
require "date"
require "json"
require "time"
require "yaml"

path, journey_id = ARGV

def log(status, message, fields = {})
  payload = {
    event: "journey_init",
    status: status,
    message: message
  }.merge(fields)
  warn(JSON.generate(payload))
end

def load_yaml(path)
  return { "journeys" => [] } unless File.exist?(path)

  YAML.safe_load(
    File.read(path),
    permitted_classes: [Date, Time],
    permitted_symbols: [],
    aliases: false
  )
rescue Psych::Exception, ArgumentError => error
  raise ArgumentError, "#{path}: #{error.message}"
end

begin
  data = load_yaml(path)
  unless data.is_a?(Hash) && data["journeys"].is_a?(Array)
    raise ArgumentError, "#{path} must contain top-level journeys: array"
  end
  if data["journeys"].any? { |journey| journey.is_a?(Hash) && journey["id"] == journey_id }
    log("failed", "journey already exists", journey_id: journey_id)
    exit 1
  end
rescue ArgumentError => error
  log("failed", error.message, journey_id: journey_id)
  exit 1
end

today = Date.today.strftime("%Y-%m-%d")
skeleton = <<~YAML
  #{File.exist?(path) && File.read(path).end_with?("\n") ? "" : "\n"}  - id: #{journey_id}
      title: "TODO: Journey title"
      persona: "TODO: Primary persona"
      related_milestone:
      related_tasks: []
      current_flow:
        - step: "TODO: Current step 1"
          pain_point: "TODO: Current pain point"
      target_flow:
        - step: "TODO: Target step 1"
          enabled_by: "TODO: Enabler"
      happy_path:
        - "TODO: Happy path step 1"
        - "TODO: Happy path step 2"
        - "TODO: Happy path step 3"
      error_paths:
        - condition: "TODO: Error condition 1"
          handling: "TODO: Handling 1"
        - condition: "TODO: Error condition 2"
          handling: "TODO: Handling 2"
      sync_status: draft
      confirmed_at:
      confirmed_by:
      created_at: #{today}
      updated_at: #{today}
      notes: "Draft skeleton generated by scripts/journeys/init.sh."
YAML

if File.exist?(path)
  text = File.read(path)
  if text.match?(/\A\s*journeys:\s*\[\]\s*(?:#.*)?\z/)
    File.write(path, "journeys:\n#{skeleton}")
  else
    File.open(path, "a") { |file| file.write(skeleton) }
  end
else
  File.write(path, "journeys:\n#{skeleton}")
end

log("ok", "journey skeleton added", journey_id: journey_id)
RUBY

init_status=$?
if [[ $init_status -ne 0 ]]; then
  exit "$init_status"
fi

if [[ -x "$VALIDATE_SCRIPT" || -f "$VALIDATE_SCRIPT" ]]; then
  JOURNEYS_FILE="$JOURNEYS_FILE" bash "$VALIDATE_SCRIPT"
fi
