#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

bash "$SCRIPT_DIR/test-day0-cleanup.sh"
bash "$SCRIPT_DIR/test-day1-manifest.sh"
bash "$SCRIPT_DIR/test-policy-core.sh"
bash "$SCRIPT_DIR/test-generated-edit-deny.sh"
bash "$SCRIPT_DIR/test-day2-policy.sh"
bash "$SCRIPT_DIR/test-week2-integrator.sh"
bash "$SCRIPT_DIR/test-events-append.sh"
bash "$SCRIPT_DIR/test-integrator-events.sh"
bash "$SCRIPT_DIR/test-week2-yaml.sh"
bash "$SCRIPT_DIR/test-week3-lease.sh"
bash "$SCRIPT_DIR/test-lease-events.sh"
bash "$SCRIPT_DIR/test-collect-events.sh"
bash "$SCRIPT_DIR/test-context-pack.sh"
bash "$SCRIPT_DIR/test-archive-tasks.sh"
bash "$SCRIPT_DIR/test-deploy-kernel-v2.sh"
bash "$SCRIPT_DIR/test-org-brief-journey.sh"
bash "$SCRIPT_DIR/test-org-tick-journey-gate.sh"
bash "$SCRIPT_DIR/test-secret-management.sh"
bash "$SCRIPT_DIR/test-doc-generators.sh"
bash "$SCRIPT_DIR/test-generate-tasks-yaml.sh"
bash "$SCRIPT_DIR/test-sqlite-schema.sh"
bash "$SCRIPT_DIR/test-import-tasks.sh"
bash "$SCRIPT_DIR/test-task-queries.sh"
bash "$SCRIPT_DIR/test-dashboard-generator.sh"
bash "$SCRIPT_DIR/test-evidence-gate.sh"
bash "$SCRIPT_DIR/test-checksum-verify.sh"
bash "$SCRIPT_DIR/test-sessionstart-checksum.sh"
bash "$SCRIPT_DIR/test-tasks-legacy-marker.sh"
bash "$SCRIPT_DIR/test-plan-contract-schema.sh"
bash "$SCRIPT_DIR/test-generate-plan.sh"
bash "$SCRIPT_DIR/test-plan-contract-required.sh"
bash "$SCRIPT_DIR/test-script-consolidation.sh"
bash "$SCRIPT_DIR/test-rule-archive.sh"
bash "$SCRIPT_DIR/test-baseline-refs.sh"
bash "$SCRIPT_DIR/test-integrator-plan-contract.sh"
bash "$SCRIPT_DIR/test-integrator-flow-fixes.sh"
bash "$SCRIPT_DIR/test-manifest-closure.sh"
bash "$SCRIPT_DIR/test-layout-migration.sh"
bash "$SCRIPT_DIR/test-reflection-loop.sh"
bash "$SCRIPT_DIR/test-scheduler-shadow.sh"
bash "$SCRIPT_DIR/../activity/run-activity-tests.sh"
